"""Integrity tests for the template placeholder manifest (slimming round 2).

dev/templates/index.yaml is machine-generated by scripts/build_template_index.py.
Its per-template `placeholders` lists let the credit-report-builder fill fields from
a manifest instead of scanning whole templates. These tests guard the extraction
against drift and the skill protocol against regression.
"""

import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = ROOT / "dev" / "templates"
INDEX = TEMPLATES_DIR / "index.yaml"
REPORT_SKILL = (
    ROOT / "dev" / ".claude" / "skills" / "credit-report-builder" / "SKILL.md"
)

# must match scripts/build_template_index.py PLACEHOLDER_RE exactly
PLACEHOLDER_RE = re.compile(
    r"\{\{\s*([A-Za-z][A-Za-z0-9_ ]*?)\s*\}\}"
    r"|\{([a-z_][a-z0-9_]*)\}"
    r"|\{([A-Z][A-Z0-9_]{2,})\}"
)


def _fresh_placeholders(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")
    return sorted({next(g for g in m.groups() if g) for m in PLACEHOLDER_RE.finditer(text)})


def _index_entries() -> list[dict]:
    data = yaml.safe_load(INDEX.read_text(encoding="utf-8"))
    entries = list(data.get("templates") or []) + list(data.get("navigation") or [])
    assert entries, "index.yaml has no template/navigation entries"
    return entries


def test_placeholder_lists_match_disk():
    """Every manifest placeholders list equals fresh extraction from the template file."""
    for entry in _index_entries():
        f = ROOT / entry["file"]
        assert f.exists(), f"{entry['file']} missing on disk"
        manifest = entry.get("placeholders") or []
        fresh = _fresh_placeholders(f)
        assert manifest == fresh, (
            f"{entry['file']}: index.yaml placeholders drift from disk "
            f"(manifest {len(manifest)} vs disk {len(fresh)}); run build_template_index.py --write"
        )


def test_placeholder_lists_sorted_unique_identifiers():
    """Manifest tokens are sorted, unique, brace-free identifiers."""
    for entry in _index_entries():
        toks = entry.get("placeholders") or []
        assert toks == sorted(set(toks)), f"{entry['file']}: not sorted/unique"
        for tok in toks:
            assert "{" not in tok and "}" not in tok, f"{entry['file']}: braces in {tok!r}"


def test_exemplar_templates_declared_empty():
    """Templates without tokens are explicit exemplar templates (empty list, not missing key)."""
    for entry in _index_entries():
        assert "placeholders" in entry, (
            f"{entry['file']}: placeholders key missing — every entry must declare "
            "a list (possibly empty for exemplar templates)"
        )


def test_report_skill_uses_manifest():
    """Drift guard: the report-builder Assembly Protocol must consume index.yaml placeholders."""
    text = REPORT_SKILL.read_text(encoding="utf-8")
    assert "index.yaml" in text, "report-builder SKILL.md must reference the placeholder manifest"
    assert "placeholders" in text, "report-builder SKILL.md must reference the placeholders list"
