#!/usr/bin/env python3
"""Regenerate dev/templates/index.yaml — the machine-readable template manifest.

Single source of truth chain: work-path-registry.md `templates` fields + the HTML
files on disk (their <title> elements) -> this generator -> index.yaml. Used by the
credit-report-builder skill (template selection), the QA verifier (template
compliance), and consistency_check (index/registry/disk agreement).

Usage:
  python scripts/build_template_index.py --write   # regenerate in place
  python scripts/build_template_index.py --check   # exit 1 if index.yaml drifts
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "dev" / "engine" / "work-path-registry.md"
TEMPLATES_DIR = ROOT / "dev" / "templates"
INDEX = TEMPLATES_DIR / "index.yaml"

sys.path.insert(0, str(ROOT))
from src.path_sheet import is_template_marker, load_registry_paths  # noqa: E402

TYPE_RE = re.compile(r"template-type(\d+)\.html$")
TITLE_RE = re.compile(r"<title>(.*?)</title>", re.DOTALL)


def build_index() -> str:
    paths = load_registry_paths(REGISTRY)
    tpl_to_paths: dict[str, list[str]] = {}
    markers: dict[str, list[str]] = {}
    for pid, entry in sorted(paths.items()):
        for tmpl in entry.get("templates") or []:
            t = str(tmpl)
            if is_template_marker(t):
                markers.setdefault(t, []).append(pid)
            else:
                tpl_to_paths.setdefault(t, []).append(pid)

    lines = [
        "# Template manifest (machine-generated by scripts/build_template_index.py; do not hand-edit)",
        "# Sources: work-path-registry.md templates fields + dev/templates/*.html <title> elements.",
        "templates:",
    ]
    for rel, pids in sorted(tpl_to_paths.items(), key=lambda kv: TYPE_RE.search(kv[0]).group(1).zfill(3)):
        name = Path(rel).name
        f = TEMPLATES_DIR / name
        title = "?"
        if f.exists():
            m = TITLE_RE.search(f.read_text(encoding="utf-8"))
            if m:
                title = " ".join(m.group(1).split())
        mtype = TYPE_RE.search(name)
        lines.append(f"  - type: {int(mtype.group(1))}")
        lines.append(f"    file: {rel}")
        lines.append(f"    title: {title!r}")
        lines.append(f"    used_by: [{', '.join(pids)}]")
        lines.append(f"    on_disk: {str(f.exists()).lower()}")
    if markers:
        lines.append("markers:")
        for marker, pids in sorted(markers.items()):
            lines.append(f"  - value: {marker!r}")
            lines.append(f"    used_by: [{', '.join(pids)}]")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    if not (args.write or args.check):
        ap.error("pass --write or --check")
    content = build_index()
    if args.write:
        if not INDEX.exists() or INDEX.read_text(encoding="utf-8") != content:
            INDEX.write_text(content, encoding="utf-8", newline="\n")
            print(f"wrote {INDEX}")
        else:
            print("index.yaml already up to date")
        return 0
    if not INDEX.exists() or INDEX.read_text(encoding="utf-8") != content:
        print("DRIFT: templates/index.yaml is stale; run --write")
        return 1
    print("template index OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
